### ISSUE TITLE
Doesn't pick up dependencies in "complex" dependency sections

### ISSUE THREAD

**Issue by MathiasPius** [MathiasPius/crates-lsp#1]
Sections like `[target.'cfg(target_os = "wasi")'.dependencies]` for exampe, are not recognized as dependency sections.

**Comment by MathiasPius** [comment]
Also doesn't match crate-specific sections like 
```toml
[dependencies.serde]
version = "1"
```
